//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hamburglar.Providers
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerFriend
    {
        public int PlayerId_1 { get; set; }
        public int PlayerId_2 { get; set; }
    }
}
