//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using GiveUp.Core;
namespace GiveUp.Core
{
    public class ActionBase
    {

        public bool IsReady { get; protected set; }
        protected ActionTimer Timer;
        public bool IsActionHappening
        {
            get;
            private set;
        }

        public event EventHandler ActionEnding;
        public event EventHandler ActionStarting;

        public ActionBase()
        {
            IsReady = true;
        }

        public virtual void StartAction()
        {
            IsActionHappening = true;
            if (ActionStarting != null)
                ActionStarting(this, EventArgs.Empty);

        }

        public virtual void Update()
        {

        }

        public virtual void EndAction()
        {
            IsActionHappening = false;
            if (ActionEnding != null)
                ActionEnding(this, EventArgs.Empty);
        }


    }
}

