//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace GiveUp.Core
{
		public class ChaseAction
		{

		public float MoveSpeed;
		Vector3 _moveDir;
		CharacterController _controller;
		GameObject ChaseTarget;

		public ChaseAction (float speed, CharacterController controller, GameObject chaseTarget)
		{
			MoveSpeed = speed;
			_controller = controller;
			ChaseTarget = chaseTarget;
		}


		public void Update()
		{
			_moveDir = Vector3.Normalize (ChaseTarget.transform.position - _controller.transform.position);
			_controller.SimpleMove (_moveDir * MoveSpeed);
		}

	}
}

